# task_0:
#  video_path: "data/video/yongen.mp4"
#  audio_path: "data/audio/yongen.wav"

task_0:
 video_path: "input.mp4"
 audio_path: "inputa.mp3"

# task_1:
#  video_path: "data/video/sun.mp4"
#  audio_path: "data/audio/sun.wav"
#  bbox_shift: -7
  

